version: "3.9" 

services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor/
        ports:
            - 80:80